### ISSUE TITLE
Numpy 2.0.0 breaks BioLogic.MPTfile()

### ISSUE THREAD

**Issue by d-cogswell** [echemdata/galvani#116]
Errors indicate that some deprecated type aliases have finally been removed:
```AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.```

Deprecated in 1.20.0: [https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations)
Removed in 2.0.0: [https://numpy.org/devdocs/release/2.0.0-notes.html#numpy-2-0-python-api-removals](https://numpy.org/devdocs/release/2.0.0-notes.html#numpy-2-0-python-api-removals)

I will prepare a PR to make these updates.

**Comment by ml-evs** [comment]
Closed by #119
