### ISSUE TITLE
Create a GitHub organization and transfer the repo

### ISSUE THREAD

**Issue by chatcannon** [echemdata/galvani#29]
To allow collaborative development work, see discussion on #26 

Create an organization: https://github.com/organizations/new

Transfer the galvani repo there: https://help.github.com/en/articles/transferring-a-repository

Add @bcolsen as a collaborator

**Comment by chatcannon** [comment]
@bcolsen The name 'galvani' is already taken, I was thinking of using 'echemdata' - do you have any better suggestions?

**Comment by bcolsen** [comment]
'echemdata' is a good name and should be googlable

'pyologic' is more 'fun' but seems limiting to biologic systems. Most of the work here is around the biologic systems. The other systems seem to use plain text or existing db formats like the arbin.

**Comment by chatcannon** [comment]
Done

**Comment by chatcannon** [comment]
@bcolsen you should now have push access to this repo
