### ISSUE TITLE
Receiving <RuntimeError: Could not locate the 'mdb-export' executable. Check that mdbtools is properly installed.> error when trying to run convert_arbin_to_sqlite method

### ISSUE THREAD

**Issue by nhshetty-99** [echemdata/galvani#41]
I'm trying to run the `convert_arbin_to_sqlite` method on one of my .res files and also specify the output file to be in a .s3db format. However, the code always fails on that line and provides me with this error:

`RuntimeError: Could not locate the 'mdb-export' executable. Check that mdbtools is properly installed.`

I then pip installed mdbtools and ran a pip freeze to see that I have version 0.3.14 installed. I also tried including an `import mdbtools` statement at the top of my file to see if that fixed the problem, but then I get this error:

`ModuleNotFoundError: No module named 'MDButils'`

I'm not sure why this is happening, so I'd appreciate any assistance or guidance from any of you. Thank you so much.

**Comment by chatcannon** [comment]
mdbtools isn't a Python package, so you can't install it with `pip install`. On Debian and Ubuntu Linux you can install it with `apt install mdbtools`.

You can see the mdbtools project on github for more info: https://github.com/brianb/mdbtools

**Comment by chatcannon** [comment]
See also #8
