### ISSUE TITLE
Fail to import some columns from data

### ISSUE THREAD

**Issue by MathildeGithub** [echemdata/galvani#59]
I obtain different results when exporting data from EClab into text format and when using .mpr file and galvani (before loading the data in a dataframe).

# Text results
Using text file, I obtain the following columns:
mode, ox/red, error, control changes, Ns changes, counter inc., Ns, time/s, dq/mA.h, (Q-Qo)/mA.h, control/V/mA, Ecell/V, I Range, Energy charge/W.h, Energy discharge/W.h, Capacitance charge/µF, Capacitance discharge/µF, I/mA, x, Q discharge/mA.h, Q charge/mA.h, Capacity/mA.h, Efficiency/%, control/V, control/mA, cycle number, P/W.
# Galvani results
Whereas with galvani from.mpr I only obtain:
'flags', 'Ns', 'time/s', 'dQ/mA.h', '(Q-Qo)/mA.h', 'control/V/mA', Ewe/V', 'I Range', 'Q charge/discharge/mA.h', 'half cycle', 'Energy charge/W.h', 'Energy discharge/W.h', 'Capacitance charge/µF', 'Capacitance discharge/µF'
# Issue
I'm unfamiliar with binary files and I found this package excellent for my purposes. The .mpr file I have is not corrupted and send no error. The missing columns are not present in the VMPdata_dtype_from_colIDs function (at least the Intensity I/mA column which I was particularly interested in,as well as P/W), so the import error must be previously in the code, such as in read_VMP_modules. My skills did not allow me to go much further than that...
Hope you can fix this!

**Comment by bcolsen** [comment]
There isn't really a problem here as far as the data extracting goes. That is all the data the binary file.

When the EClab software exports the file it reads the mpr and calculates the extra column values. There is no data in the mprs to tell us what extra columns to compute and they are different for every test type. The mpr doesn't even tell what data columns in the file either. That is all reverse engineered.  Almost all test types calculate some extra data columns.

Good news is that once everything is in python calculating things is easy. Power is Ewe/V * control/V/mA and it looks like <I> is dQ / dt where dt is the diff(np.diff) of time in hours(best I can figure. Not well tested. Try it out).  The control isn't always the current depending on the step but there is a way to figure that out using the flags.

**Comment by MathildeGithub** [comment]
Thanks a lot for your answer. It's indeed rather easy to calculate, I just wanted to make sure it was the right path forward!
