### ISSUE TITLE
[MPR File] ValueError: time data 'XX.XX.XX' does not match format '%m-%d-%y'

### ISSUE THREAD

**Issue by regcs** [echemdata/galvani#60]
Hi, I tried using Galvani for the first time and when trying to load the mpr file from a BioLogic potentiostat, it raises the following exception:

```
ValueError: time data '11.12.20' does not match format '%m/%d/%y'
ValueError: time data '11.12.20' does not match format '%m-%d-%y'
```

It seems like my date format uses dots instead of "/" or "-". Don't know if it has to do with my EC-Labs settings or maybe that the date format of the OS is set to using "." (which is the standard for German date format).

I changed lines 398ff. in "BioLogic.py" to 

```
try:
  tm = time.strptime(settings_mod['date'].decode('ascii'), '%m/%d/%y')
except ValueError:
  try:
      tm = time.strptime(settings_mod['date'].decode('ascii'), '%m-%d-%y')
  except ValueError:
      tm = time.strptime(settings_mod['date'].decode('ascii'), '%m.%d.%y')
```
 
and the same for the similar lines 418ff. which solved the problem. Maybe you want to integrate the additional date format in Galvani, @chatcannon. 

BTW: Thanks a lot for this really nice python package! :)

**Comment by chatcannon** [comment]
Are you sure it's `%m.%d.%y` and not `%d.%m.%y` which would be more normal for Germany? "11.12.20" is potentially valid in both formats.

**Comment by regcs** [comment]
Didn't spend to much attention to that. You are right, for Germany the day would be in front. But the data was indeed recorded on November 12th, 2020. So, it is a weird mixture ...
