### ISSUE TITLE
NotImplementedError: Column ID 174 after column control/mA is unknown (similar to #64)

### ISSUE THREAD

**Issue by Etruria89** [echemdata/galvani#67]
I was trying to read one .mpr file and it was continuously generating the following errors:

1)'NotImplementedError: Column ID 174 after column control/mA is unknown'
BioLogic.py script modified and it is now reading the .mpr file correctly:
Here below the change:
(line 186)         174: ('Ewe/V', '<f4'), added.

At the moment I am reading properly also all the other files.

Please double-check if this change can be pushed
[Test_error.zip](https://github.com/echemdata/galvani/files/7574282/Test_error.zip)
?

**Comment by ilka-schulz** [comment]
@chatcannon Should it not be `<Ewe>/V`? I think it is the *averaged* voltage (WE vs. REF). Also see my comment here https://github.com/echemdata/galvani/issues/74#issuecomment-1318221478. PM me for an example `.mpr` and `.mpt` file pair.
