### ISSUE TITLE
Error when opening *mpr file: 'NotImplementedError: Column ID 27 after column control/mA is unknown'

### ISSUE THREAD

**Issue by pioja-dtu** [echemdata/galvani#74]
I'm trying to open .mpr files using the galvani library.
When opening files of GCPL technique of BioLogic, everything is fine.
However, when opening files after the GCPL2 technique, I got error:

NotImplementedError: Column ID 27 after column control/mA is unknown

Looks like this file has some extra, unexpected column.
Is there a way to make this column recognizable and be able to read the file with Galvani?

**Comment by chatcannon** [comment]
Hello and sorry for not responding for so long. If your data are not secret, please could you provide me with a .mpr file that triggers this problem and a corresponding .mpt file produced by loading the same data in the BioLogic software and exporting?

**Comment by chatcannon** [comment]
If you cannot provide me with the raw data, then please do the same process of exporting the .mpt file, then open the .mpt file in a text editor, look for the column headers and tell me which one comes after "control/mA".

**Comment by pioja-dtu** [comment]
Hello, thanks for your reply and sorry for no answering - not so often here...
I noticed similar error when trying to load data when the measurement also records some input from external devices (IN 1 and IN 2).
Please see the attached filles for both cases.
Would be really cool if that could be implemented in next version of 
[biologic files.zip](https://github.com/echemdata/galvani/files/9901871/biologic.files.zip)
galvani.
[biologic files.zip](https://github.com/echemdata/galvani/files/9901871/biologic.files.zip)

**Comment by ilka-schulz** [comment]
Any progress on this issue? I have a similar problem:
```text
NotImplementedError: Column ID 174 after column control/mA is unknown
```
I will have a closer look at the problem myself. Maybe I can open a PR.

**Comment by ilka-schulz** [comment]
@pioja-dtu I think I found some good results but could you please review my methodology to ensure my findings are correct? Give me a thump up :+1: if my methodology is correct so I can create a PR.

### Results
#### Column 27
This is `Ewe-Ece/V` which is described as `E we -E ce : WE versus CE potential` in the manual. The values seem to be 32 bit floats. It is currently not included in in the `galvani.BioLogic.VMPdata_colID_dtype_map` dictionary.

#### Column 174
This is `<Ewe>/V` which is described as `<E we> : averaged voltage (WE vs. REF)` in the manual. The values seem to be 32 bit floats. However, there is already a record named `<Ewe>/V` in the `galvani.BioLogic.VMPdata_colID_dtype_map` dictionary under the key `77`. PM me if you need a the file pair.

### Methodology
I used EC-Lab 11.36 to generate an `.mpt` file from my `.mpr` file. I then fetched the column name after the one mentioned in the error message from the `.mpt` file.

**Comment by ilka-schulz** [comment]
I find that Column 174 was already added in c1e5d92ed08d2fd9e245c419d267ec807a4991b4 but this commit is not yet included in a release. I guess my methodology is correct then...

**Comment by pioja-dtu** [comment]
Your descriptions look more than correct to me!

**Comment by ilario** [comment]
I also had unrecognized columns when using the latest release but not when using the development code.
@echemdata @chatcannon is a new release planned?
Thanks for the very useful piece of software!
