### ISSUE TITLE
NotImplementedError: Column ID 509 after column Rdc/Ohm is unknown

### ISSUE THREAD

**Issue by js1tr3** [echemdata/galvani#76]
Trying to add 'Acir/Dcir Control', but I failed, example mpr and mpt can be found at the attached links.  

https://drive.google.com/file/d/1DZ7tvy2EOntFyqlfnam-CL6AhmaJGAl1/view?usp=sharing
https://drive.google.com/file/d/1BIHCRX_ja-4tqGGLpkHK-I0ESMnbOsOQ/view?usp=sharing

**Comment by Paulemeister** [comment]
I have a pull request #88 open, adding ID 509 Acir/Dcir Control

**Comment by chatcannon** [comment]
PR merged
