### ISSUE TITLE
Unable to read res files with mdbtools>=1.0

### ISSUE THREAD

**Issue by ml-evs** [echemdata/galvani#89]
Using mdbtools v1.0 with galvani leads to the following error when parsing .res files:

```python    
s3db = <sqlite3.Connection object at 0x7fd2bc033840>
filename = '/home/runner/work/navani/navani/tests/../Example_data/arbin_example.res'
table = 'Event_Table'

    def mdb_get_data_text(s3db, filename, table):
        print("Reading %s..." % table)
        insert_pattern = re.compile(
            r'INSERT INTO "\w+" \([^)]+?\) VALUES \(("[^"]*"|[^")])+?\);\n',
            re.IGNORECASE
        )
        try:
            # Initialize values to avoid NameError in except clause
            mdb_output = ''
            insert_match = None
            with sp.Popen(['mdb-export', '-I', 'postgres', filename, table],
                          bufsize=-1, stdin=sp.DEVNULL, stdout=sp.PIPE,
                          universal_newlines=True) as mdb_sql:
    
                mdb_output = mdb_sql.stdout.read()
                while len(mdb_output) > 0:
                    insert_match = insert_pattern.match(mdb_output)
>                   s3db.execute(insert_match.group())
E                   AttributeError: 'NoneType' object has no attribute 'group'

../../../.local/share/virtualenvs/navani-KXBeI0hV/lib/python3.10/site-packages/galvani/res2sqlite.py:455: AttributeError
```

On Ubuntu 22.04, mdbtools v1 is now the default version (whereas it capped out at 0.7 on 20.04). I'm happy to investigate this failure in detail on the mdbtools side and see if there is an easy way to add support for both versions in this repo, but if someone sees this first and knows what is going on, feel free to take over! 

You can see this clearly in the status checks of https://github.com/the-grey-group/navani/pull/4, where all I am changing in the last few commits is the base image of our CI.

As a side note, it would be nice to have CI running in this repo again, as it still seems to have active use. I'm happy to set this up on GitHub actions as I can't tell if Travis is still running anywhere. Probably this would need a maintainer of the repository to enable the workflows for this repo (I will make a separate issue).

**Comment by chatcannon** [comment]
Here I have done the classic programming WTF of parsing text with regular expressions. I guess the output format of mdbtools has changed so the original regex is no longer valid.

Ideally we want a native Python (or Cython extension) parser for MDB so we don't have to call out to this external program. I started on that and posted my work at https://gitlab.com/cymdb but realistically it would probably be better to start over.

**Comment by ml-evs** [comment]
I was planning on doing the bare minimum here and at least adding a check for the mdbtools version before attempting to extract, with a more helpful error message if it fails. We might be able to get away with just invoking mbdtools differently (the latest version that works here without further changes is about 10 years old...)

**Comment by chatcannon** [comment]
10 years ago is not coincidentally the last time I touched a battery cycler...
